services:
  app:
    image: ghcr.io/yazdipour/telestore:${TELESTORE_IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    volumes:
      - telegram-session:/data
      - ./config.yml:/app/config.yml
    restart: unless-stopped

volumes:
  telegram-session:
