name: telestore

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - telegram-session:/data
      - ./config.yml:/app/config.yml
    restart: unless-stopped

volumes:
  telegram-session:
